import { NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';
import { ok, err } from '@/lib/utils';
import { requireMtcEditor } from '@/lib/auth';

// POST /api/mtc/opname/[id]/post - ACC & Post Stock Opname Adjustments
export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const sessionUser = await requireMtcEditor();
    if (!sessionUser) return err('Hanya Supervisor / Editor MTC yang diizinkan meng-ACC & Posting Stock Opname.', 403);

    const sessionId = parseInt(params.id);
    if (isNaN(sessionId)) return err('ID sesi tidak valid', 400);

    const session = await prisma.opnameSession.findUnique({
      where: { id: sessionId },
      include: { items: true }
    });

    if (!session) return err('Sesi Stock Opname tidak ditemukan', 404);
    if (session.status === 'POSTED') {
      return err('Sesi Stock Opname ini sudah di-ACC & di-posting sebelumnya.', 400);
    }

    const itemsToAdjust = session.items.filter(item => item.qtyFisik !== null && item.qtyFisik !== undefined && item.selisih !== 0);

    const auditorName = sessionUser.user?.name || sessionUser.user?.email || 'Supervisor MTC';

    // Transaction to update session and post StockMovements
    await prisma.$transaction(async (tx) => {
      // 1. Mark OpnameSession as POSTED
      await tx.opnameSession.update({
        where: { id: sessionId },
        data: {
          status: 'POSTED',
          approvedBy: auditorName,
          approvedAt: new Date()
        }
      });

      // 2. Batch fetch sparepart prices for financial valuation accuracy
      const spIds = itemsToAdjust.map(i => i.sparepartId).filter(Boolean) as string[];
      const spareparts = spIds.length > 0 ? await tx.sparepart.findMany({
        where: { id: { in: spIds } },
        select: { id: true, harga: true, lokasi: true, tipeUkur: true }
      }) : [];
      const spMap = new Map(spareparts.map(s => [s.id, s]));

      // 3. Create StockMovement adjustments for items with variance
      for (const item of itemsToAdjust) {
        const isPlus = item.selisih > 0;
        const movementQty = Math.abs(item.selisih);
        const sp = item.sparepartId ? spMap.get(item.sparepartId) : null;
        const itemHarga = sp ? Number(sp.harga) : 0;

        await tx.stockMovement.create({
          data: {
            tipe: isPlus ? 'IN' : 'OUT',
            sparepartId: item.sparepartId || null,
            namaItem: item.namaItem,
            qty: movementQty,
            harga: itemHarga,
            lokasi: item.lokasi || sp?.lokasi || 'Gudang MTC',
            keterangan: `[OPNAME] Adjustment Hasil Audit Sesi #${sessionId} - "${session.judul}" (${isPlus ? '+' : '-'}${movementQty} ${item.uom})`,
            tanggal: new Date()
          }
        });

        // Jika barang bertipe bulk dan surplus (+), catat potongan fisik baru dari opname
        if (isPlus && sp && sp.tipeUkur === 'bulk') {
          await tx.potonganFisik.create({
            data: {
              sparepartId: sp.id,
              panjangAwal: movementQty,
              panjangSisa: movementQty,
              asal: `Stock Opname #${sessionId} (${session.judul})`,
              tanggalMasuk: new Date(),
              status: 'aktif',
            },
          });
        }
      }
    });

    return ok({
      msg: `✓ Sesi Stock Opname #${sessionId} ("${session.judul}") berhasil di-ACC & Di-Posting! Total ${itemsToAdjust.length} item penyesuaian stok telah diperbarui.`
    });
  } catch (e: any) {
    console.error('Error posting opname session:', e);
    return err('Gagal meng-ACC & posting Stock Opname: ' + e.message, 500);
  }
}

// DELETE /api/mtc/opname/[id]/post - Rollback / Un-ACC Stock Opname Session back to DRAFT
export async function DELETE(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const sessionUser = await requireMtcEditor();
    if (!sessionUser) return err('Hanya Supervisor / Editor MTC yang diizinkan membatalkan ACC Stock Opname.', 403);

    const sessionId = parseInt(params.id);
    if (isNaN(sessionId)) return err('ID sesi tidak valid', 400);

    const session = await prisma.opnameSession.findUnique({
      where: { id: sessionId }
    });

    if (!session) return err('Sesi Stock Opname tidak ditemukan', 404);

    await prisma.$transaction(async (tx) => {
      // 1. Rollback & delete all StockMovements generated by this session posting
      await tx.stockMovement.deleteMany({
        where: {
          keterangan: { startsWith: `[OPNAME] Adjustment Hasil Audit Sesi #${sessionId}` }
        }
      });

      // 2. Rollback & delete PotonganFisik created by this opname session
      await tx.potonganFisik.deleteMany({
        where: {
          asal: `Stock Opname #${sessionId} (${session.judul})`
        }
      });

      // 3. Reset session status back to DRAFT
      await tx.opnameSession.update({
        where: { id: sessionId },
        data: {
          status: 'DRAFT',
          approvedBy: null,
          approvedAt: null
        }
      });
    });

    return ok({
      msg: `✓ Sesi Stock Opname #${sessionId} ("${session.judul}") berhasil di-Reset / Dibatalkan ACC-nya! Status kembali ke DRAFT.`
    });
  } catch (e: any) {
    console.error('Error unposting opname session:', e);
    return err('Gagal membatalkan ACC Stock Opname: ' + e.message, 500);
  }
}
