#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE mtc_db;
  CREATE DATABASE ga_db;
  GRANT ALL PRIVILEGES ON DATABASE mtc_db TO $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON DATABASE ga_db TO $POSTGRES_USER;
EOSQL
