-- AlterTable
ALTER TABLE "mesin" ADD COLUMN IF NOT EXISTS "tipe" TEXT NOT NULL DEFAULT 'keduanya';

-- AlterTable
ALTER TABLE "sparepart" ADD COLUMN IF NOT EXISTS "max_lead_time" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "sparepart" ADD COLUMN IF NOT EXISTS "avg_lead_time" DOUBLE PRECISION NOT NULL DEFAULT 0;
